// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIHNfRwgccV6eXttyZazR_Nku_iQ1sdW4',
    appId: '1:757279414559:web:3aa29d2a70c678556b782a',
    messagingSenderId: '757279414559',
    projectId: 'nepal-engineering-college-app',
    authDomain: 'nepal-engineering-college-app.firebaseapp.com',
    storageBucket: 'nepal-engineering-college-app.firebasestorage.app',
    measurementId: 'G-G8KGYFQ76C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyRGGg48A8ujXqU32GuHBR_Ao4pivkvYc',
    appId: '1:757279414559:android:4e876fccc57f09416b782a',
    messagingSenderId: '757279414559',
    projectId: 'nepal-engineering-college-app',
    storageBucket: 'nepal-engineering-college-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCcc6ehq6_NHP4KcGsiPDmL1fh4T0WVA',
    appId: '1:757279414559:ios:10981280eb86cea06b782a',
    messagingSenderId: '757279414559',
    projectId: 'nepal-engineering-college-app',
    storageBucket: 'nepal-engineering-college-app.firebasestorage.app',
    iosBundleId: 'com.example.necApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnCcc6ehq6_NHP4KcGsiPDmL1fh4T0WVA',
    appId: '1:757279414559:ios:10981280eb86cea06b782a',
    messagingSenderId: '757279414559',
    projectId: 'nepal-engineering-college-app',
    storageBucket: 'nepal-engineering-college-app.firebasestorage.app',
    iosBundleId: 'com.example.necApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIHNfRwgccV6eXttyZazR_Nku_iQ1sdW4',
    appId: '1:757279414559:web:215c5017b5e5fe486b782a',
    messagingSenderId: '757279414559',
    projectId: 'nepal-engineering-college-app',
    authDomain: 'nepal-engineering-college-app.firebaseapp.com',
    storageBucket: 'nepal-engineering-college-app.firebasestorage.app',
    measurementId: 'G-5D8V7F69V2',
  );

}